-- HarvestChanges
-- Author: makak
-- DateCreated: 2019-12-18 8:58:11
--------------------------------------------------------------

-- this file deals with making all resources harvestable

-----------------------
-- Resource_Harvests --
-----------------------

-- truncate table
DELETE FROM Resource_Harvests;

INSERT INTO Resource_Harvests (ResourceType, YieldType, Amount, PrereqTech)
VALUES
	('RESOURCE_HORSES',				'YIELD_PRODUCTION',		20,		'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_IRON',				'YIELD_PRODUCTION',		20,		'TECH_BRONZE_WORKING'),
	('RESOURCE_NITER',				'YIELD_PRODUCTION',		40,		'TECH_MILITARY_ENGINEERING'),
	('RESOURCE_COAL',				'YIELD_PRODUCTION',		40,		'TECH_INDUSTRIALIZATION'),
	('RESOURCE_ALUMINUM',			'YIELD_PRODUCTION',		60,		'TECH_RADIO'),
	('RESOURCE_OIL',				'YIELD_PRODUCTION',		60,		'TECH_PLASTICS'),
	('RESOURCE_URANIUM',			'YIELD_PRODUCTION',		80,		'TECH_COMBINED_ARMS'),
	('RESOURCE_AMBER',				'YIELD_GOLD',			20,		'TECH_MINING'),
	('RESOURCE_DIAMONDS',			'YIELD_GOLD',			20,		'TECH_MINING'),
	('RESOURCE_JADE',				'YIELD_GOLD',			20,		'TECH_MINING'),
	('RESOURCE_MERCURY',			'YIELD_GOLD',			20,		'TECH_MINING'),
	('RESOURCE_SALT',				'YIELD_GOLD',			20,		'TECH_MINING'),
	('RESOURCE_SILVER',				'YIELD_GOLD',			20,		'TECH_MINING'),
	('RESOURCE_MARBLE',				'YIELD_GOLD',			20,		'TECH_MASONRY'),
	('RESOURCE_GYPSUM',				'YIELD_GOLD',			20,		'TECH_MASONRY'),
	('RESOURCE_TURTLES',			'YIELD_GOLD',			20,		'TECH_CELESTIAL_NAVIGATION'),
	('RESOURCE_PEARLS',				'YIELD_GOLD',			20,		'TECH_CELESTIAL_NAVIGATION'),
	('RESOURCE_WHALES',				'YIELD_GOLD',			20,		'TECH_CELESTIAL_NAVIGATION'),
	('RESOURCE_CITRUS',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_COCOA',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_COTTON',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_DYES',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_INCENSE',			'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_SILK',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_SPICES',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_SUGAR',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_TEA',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_COFFEE',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_TOBACCO',			'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_WINE',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_FURS',				'YIELD_GOLD',			20,		'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_IVORY',				'YIELD_GOLD',			20,		'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_TRUFFLES',			'YIELD_GOLD',			20,		'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_OLIVES',				'YIELD_GOLD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_WHEAT',				'YIELD_FOOD',			20,		'TECH_POTTERY'),
	('RESOURCE_RICE',				'YIELD_FOOD',			20,		'TECH_POTTERY'),
	('RESOURCE_BANANAS',			'YIELD_FOOD',			20,		'TECH_IRRIGATION'),
	('RESOURCE_FISH',				'YIELD_FOOD',			20,		'TECH_CELESTIAL_NAVIGATION'),
	('RESOURCE_CRABS',				'YIELD_FOOD',			20,		'TECH_CELESTIAL_NAVIGATION'),
	('RESOURCE_CATTLE',				'YIELD_FOOD',			20,		'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_SHEEP',				'YIELD_FOOD',			20,		'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_DEER',				'YIELD_FOOD',			20,		'TECH_ANIMAL_HUSBANDRY'),
	('RESOURCE_COPPER',				'YIELD_PRODUCTION',		20,		'TECH_MINING'),
	('RESOURCE_STONE',				'YIELD_PRODUCTION',		20,		'TECH_MASONRY'),
	('RESOURCE_ANTIQUITY_SITE',		'YIELD_CULTURE',		40,		'TECH_RADIO'),
	('RESOURCE_SHIPWRECK',			'YIELD_CULTURE',		60,		'TECH_RADIO');